# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-23 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='name',
            new_name='resource_name',
        ),
        migrations.AlterField(
            model_name='entry',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='blog_image/%Y%m', verbose_name='博客配图'),
        ),
    ]
