# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-23 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190623_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='download_num',
            field=models.PositiveIntegerField(default=0, verbose_name='博客访问量'),
        ),
    ]
