# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-23 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_entry_download_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_body',
            field=models.TextField(max_length=200, verbose_name='评论'),
        ),
    ]
